services:
  wedding_web:
    image: node:20.18.1
    container_name: wedding_web
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - ./wedding-web:/usr/src/app
    networks:
      - wedding_network
    command: >
      sh -c "(npm install || echo 'npm install failed') &&
            (npm run build || echo 'npm build failed') &&
            (npm run start || echo 'npm start failed')"

  wedding_nginx:
    image: nginx:stable-perl
    container_name: wedding_nginx
    ports:
      - 80:80
    depends_on:
      - wedding_web
    networks:
      - wedding_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    
networks:
  wedding_network:
    driver: bridge 